[package]
name = "tiled_render_experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
bevy_prototype_lyon = "0.6.0"
crossbeam-channel = "0.5.5"
futures-lite = "1.12.0"
geo = "0.22.1"
csv = "1.1.6"
bitflags = "1.3.2"
itertools = "0.10.3"
rkyv = "0.7.39"
memmap2 = "0.5.6"

[profile.dev.package."*"]
opt-level = 1

# [profile.release]
# debug = true
